= meals-api documentation
Joseph Cosentino
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

[[overview-http-verbs]]
== HTTP verbs

|===
| Verb | Usage

| `GET`
| Used to retrieve a resource

| `POST`
| Used to create a new resource

| `PATCH`
| Used to update an existing resource, including partial updates

| `DELETE`
| Used to delete an existing resource
|===

[[overview-http-status-codes]]
== HTTP status codes

|===
| Status code | Usage

| `200 OK`
| The request completed successfully

| `201 Created`
| A new resource has been created successfully. The resource's URI is available from the response's
`Location` header

| `204 No Content`
| An update to an existing resource has been applied successfully

| `400 Bad Request`
| The request was malformed. The response body will include an error providing further information

| `404 Not Found`
| The requested resource did not exist
|===

[[resources]]
= Resources

[[resources-user]]
== User

The users resource is used for retrieving users

[[resources-user-findAll]]
=== Find all users

A `GET` request is used to retrieve all users

operation::user-findAll[snippets='curl-request,http-response,request-parameters,request-headers,response-fields']

[[resources-user-findById]]
=== Find user by id

A `GET` request is used to retrieve a user by id

operation::user-findById[snippets='curl-request,http-response,path-parameters,request-headers,response-fields']

[[resources-user-clearCache]]
=== Clear user cache

A `DELETE` request is used to clear the user cache

operation::user-clearCache[snippets='curl-request,http-response,request-headers']

[[resources-user-clearCacheById]]
=== Clear user cache by id

A `DELETE` request is used to clear the user cache by id

operation::user-clearCacheById[snippets='curl-request,http-response,request-headers']

[[resources-group]]
== Group

The groups resource is used for retrieving groups

[[resources-group-findAll]]
=== Find all groups

A `GET` request is used to retrieve all groups

operation::group-findAll[snippets='curl-request,http-response,request-parameters,request-headers,response-fields']

[[resources-group-findById]]
=== Find group by id

A `GET` request is used to retrieve a group by id

operation::group-findById[snippets='curl-request,http-response,path-parameters,request-headers,response-fields']

[[resources-group-findUsers]]
=== Find a group's users

A `GET` request is used to retrieve a group's users

operation::group-findUsers[snippets='curl-request,http-response,path-parameters,request-headers,response-fields']

[[resources-group-clearCache]]
=== Clear group cache

A `DELETE` request is used to clear the group cache

operation::group-clearCache[snippets='curl-request,http-response,request-headers']

[[resources-group-clearCacheById]]
=== Clear group cache by id

A `DELETE` request is used to clear the group cache by id

operation::group-clearCacheById[snippets='curl-request,http-response,request-headers']