INSERT INTO USERS (USER_ID, USERNAME, PASSWORD) VALUES (1, 'test-user', 'pwd');
INSERT INTO GROUPS (GROUP_ID, NAME) VALUES (1, 'test-group');
INSERT INTO USERS_GROUPS (GROUP_ID, USER_ID) VALUES (1, 1);